In [ ]:
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras import layers
from tqdm import tqdm
import matplotlib.pyplot as plt
from tqdm import tqdm
import foolbox as fb


tf.compat.v1.enable_eager_execution()
tf.keras.backend.clear_session()  # For easy reset of notebook state.

# Prune, Train Attack Pipeline

In [9]:
pgd_success_rates = []
cw_success_rates = []
all_accuracies = []
for j in tqdm(range(10)):
    accuracies = []
    pgd_success_rate = []
    cw_success_rate = []
    pruning_ratios = [.0, .3, .5, .7, .8, .9, .95, .97, .98]
    for index, pruning_ratio in tqdm(enumerate(pruning_ratios)):
        model = tf.keras.models.load_model('./saved-models/mini-pipeline-baseline-model')
        for i in range(index + 1):
            if i != index:
                pruned_weights = prune_weights(model, pruning_ratios[i])
                model.set_weights(pruned_weights)
                model = train_model(model, to_convergence=False)
            if i == index:
                print('final pruning and eval')
                pruned_weights = prune_weights(model, pruning_ratios[i])
                model.set_weights(pruned_weights)
                model = train_model(model, to_convergence=True)
                accuracies.append(model.evaluate(x_test, y_test, verbose=0))
                pgd_success_rate.append(pgd_attack(model))
                cw_success_rate.append(cw2_attack(model))
                
    all_accuracies.append(accuracies)
    pgd_success_rates.append(pgd_success_rate)
    cw_success_rates.append(cw_success_rate)


  0%|          | 0/10 [00:00<?, ?it/s]
0it [00:00, ?it/s]

final pruning and eval
Train on 60000 samples, validate on 10000 samples
Epoch 1/100
60000/60000 [==============================] - 5s 82us/sample - loss: 1.4984 - accuracy: 0.9644 - val_loss: 1.4965 - val_accuracy: 0.9659
Epoch 2/100
60000/60000 [==============================] - 5s 76us/sample - loss: 1.4907 - accuracy: 0.9717 - val_loss: 1.4923 - val_accuracy: 0.9688
Epoch 3/100
60000/60000 [==============================] - 4s 69us/sample - loss: 1.4865 - accuracy: 0.9758 - val_loss: 1.4898 - val_accuracy: 0.9719
Epoch 4/100
60000/60000 [==============================] - 4s 70us/sample - loss: 1.4831 - accuracy: 0.9789 - val_loss: 1.4901 - val_accuracy: 0.9712
Epoch 5/100
60000/60000 [==============================] - 5s 76us/sample - loss: 1.4806 - accuracy: 0.9811 - val_loss: 1.4894 - val_accuracy: 0.9728
Epoch 6/100
60000/60000 [==============================] - 4s 66us/sample - loss: 1.4791 - accuracy: 0.9825 - val_loss: 1.4853 - val_accuracy: 0.9762
Epoch 7/100
60000/60000 [==


1it [11:28, 688.44s/it]

self.p 2
flatten(p) TensorFlowTensor(<tf.Tensor: shape=(500, 784), dtype=float32, numpy=
                 array([[1.1920929e-07, 1.7522573e-03, 9.1007352e-04, ..., 0.0000000e+00,
                         5.9604645e-08, 2.9802322e-08],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        ...,
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00]], dtype

Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 6s 101us/sample - loss: 1.4983 - accuracy: 0.9646 - val_loss: 1.5001 - val_accuracy: 0.9634
Epoch 2/2
60000/60000 [==============================] - 5s 80us/sample - loss: 1.4906 - accuracy: 0.9718 - val_loss: 1.4946 - val_accuracy: 0.9674
final pruning and eval
Train on 60000 samples, validate on 10000 samples
Epoch 1/100
60000/60000 [==============================] - 5s 89us/sample - loss: 1.4835 - accuracy: 0.9787 - val_loss: 1.4896 - val_accuracy: 0.9721
Epoch 2/100
60000/60000 [==============================] - 6s 96us/sample - loss: 1.4804 - accuracy: 0.9816 - val_loss: 1.4885 - val_accuracy: 0.9731
Epoch 3/100
60000/60000 [==============================] - 5s 78us/sample - loss: 1.4792 - accuracy: 0.9828 - val_loss: 1.4873 - val_accuracy: 0.9745
Epoch 4/100
60000/60000 [==============================] - 4s 72us/sample - loss: 1.4772 - accuracy: 0.9845 - val_loss: 1.4859 - v


2it [23:13, 693.36s/it]

self.p 2
flatten(p) TensorFlowTensor(<tf.Tensor: shape=(500, 784), dtype=float32, numpy=
                 array([[0., 0., 0., ..., 0., 0., 0.],
                        [0., 0., 0., ..., 0., 0., 0.],
                        [0., 0., 0., ..., 0., 0., 0.],
                        ...,
                        [0., 0., 0., ..., 0., 0., 0.],
                        [0., 0., 0., ..., 0., 0., 0.],
                        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>)
norms TensorFlowTensor(<tf.Tensor: shape=(500,), dtype=float32, numpy=
                 array([9.55769634e+00, 1.01887922e+01, 7.69860315e+00, 7.64230442e+00,
                        8.78968334e+00, 9.82331848e+00, 7.84854794e+00, 1.10874434e+01,
                        5.97471809e+00, 8.43502331e+00, 9.91496086e+00, 6.75492477e+00,
                        1.10000086e+01, 9.63416100e+00, 6.21040058e+00, 9.20947552e+00,
                        8.95141888e+00, 9.41311455e+00, 6.35417938e+00, 7.56579924e+00,
                       

Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 72us/sample - loss: 1.4990 - accuracy: 0.9639 - val_loss: 1.5045 - val_accuracy: 0.9572
Epoch 2/2
60000/60000 [==============================] - 4s 69us/sample - loss: 1.4905 - accuracy: 0.9721 - val_loss: 1.4925 - val_accuracy: 0.9698
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 67us/sample - loss: 1.4841 - accuracy: 0.9781 - val_loss: 1.4875 - val_accuracy: 0.9743
Epoch 2/2
60000/60000 [==============================] - 4s 67us/sample - loss: 1.4805 - accuracy: 0.9816 - val_loss: 1.4870 - val_accuracy: 0.9752
final pruning and eval
Train on 60000 samples, validate on 10000 samples
Epoch 1/100
60000/60000 [==============================] - 4s 67us/sample - loss: 1.4774 - accuracy: 0.9847 - val_loss: 1.4835 - val_accuracy: 0.9782
Epoch 2/100
60000/60000 [==============================] - 4s 67us/sample - loss: 1.4


3it [36:53, 731.44s/it]

self.p 2
flatten(p) TensorFlowTensor(<tf.Tensor: shape=(500, 784), dtype=float32, numpy=
                 array([[1.7881393e-07, 1.7881393e-07, 2.3841858e-07, ..., 1.4901161e-07,
                         9.2387199e-07, 1.7881393e-07],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        ...,
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00]], dtype

Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 5s 86us/sample - loss: 1.4987 - accuracy: 0.9643 - val_loss: 1.4955 - val_accuracy: 0.9669
Epoch 2/2
60000/60000 [==============================] - 5s 80us/sample - loss: 1.4908 - accuracy: 0.9716 - val_loss: 1.4934 - val_accuracy: 0.9688
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 75us/sample - loss: 1.4838 - accuracy: 0.9783 - val_loss: 1.4879 - val_accuracy: 0.9733
Epoch 2/2
60000/60000 [==============================] - 5s 75us/sample - loss: 1.4809 - accuracy: 0.9812 - val_loss: 1.4853 - val_accuracy: 0.9772
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 5s 77us/sample - loss: 1.4775 - accuracy: 0.9847 - val_loss: 1.4850 - val_accuracy: 0.9765
Epoch 2/2
60000/60000 [==============================] - 5s 78us/sample - loss: 1.4755 - accuracy: 0.9866 - va


4it [53:59, 819.93s/it]

self.p 2
flatten(p) TensorFlowTensor(<tf.Tensor: shape=(500, 784), dtype=float32, numpy=
                 array([[1.4901161e-07, 3.6954880e-06, 5.3644180e-07, ..., 1.6093254e-06,
                         1.7881393e-07, 5.9604645e-08],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [8.3446503e-07, 1.0132790e-06, 8.3446503e-07, ..., 1.0728836e-06,
                         1.1324883e-06, 1.1622906e-06],
                        ...,
                        [1.6987324e-06, 2.9802322e-07, 8.9406967e-07, ..., 2.3841858e-07,
                         5.9604645e-07, 1.7881393e-07],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00]], dtype

Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 5s 80us/sample - loss: 1.4987 - accuracy: 0.9639 - val_loss: 1.4985 - val_accuracy: 0.9636
Epoch 2/2
60000/60000 [==============================] - 4s 73us/sample - loss: 1.4905 - accuracy: 0.9718 - val_loss: 1.4935 - val_accuracy: 0.9689
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 70us/sample - loss: 1.4843 - accuracy: 0.9781 - val_loss: 1.4873 - val_accuracy: 0.9746
Epoch 2/2
60000/60000 [==============================] - 4s 71us/sample - loss: 1.4815 - accuracy: 0.9804 - val_loss: 1.4856 - val_accuracy: 0.9760
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 5s 75us/sample - loss: 1.4777 - accuracy: 0.9846 - val_loss: 1.4856 - val_accuracy: 0.9758
Epoch 2/2
60000/60000 [==============================] - 4s 72us/sample - loss: 1.4751 - accuracy: 0.9869 - va


5it [1:06:33, 799.95s/it]

self.p 2
flatten(p) TensorFlowTensor(<tf.Tensor: shape=(500, 784), dtype=float32, numpy=
                 array([[7.1004033e-04, 0.0000000e+00, 4.7683716e-07, ..., 1.3400316e-03,
                         6.8545341e-07, 1.1920929e-07],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [1.5497208e-06, 1.5795231e-06, 1.1920929e-06, ..., 2.8312206e-06,
                         1.4007092e-06, 1.8477440e-06],
                        ...,
                        [1.4901161e-07, 1.7881393e-07, 4.7683716e-07, ..., 1.1920929e-07,
                         1.6689301e-06, 1.4901161e-07],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00]], dtype

Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 69us/sample - loss: 1.4977 - accuracy: 0.9653 - val_loss: 1.4963 - val_accuracy: 0.9660
Epoch 2/2
60000/60000 [==============================] - 4s 62us/sample - loss: 1.4906 - accuracy: 0.9717 - val_loss: 1.4919 - val_accuracy: 0.9699
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 61us/sample - loss: 1.4839 - accuracy: 0.9783 - val_loss: 1.4870 - val_accuracy: 0.9748
Epoch 2/2
60000/60000 [==============================] - 4s 64us/sample - loss: 1.4806 - accuracy: 0.9814 - val_loss: 1.4896 - val_accuracy: 0.9724
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 62us/sample - loss: 1.4771 - accuracy: 0.9852 - val_loss: 1.4843 - val_accuracy: 0.9775
Epoch 2/2
60000/60000 [==============================] - 4s 63us/sample - loss: 1.4753 - accuracy: 0.9867 - va


6it [1:19:21, 790.55s/it]

self.p 2
flatten(p) TensorFlowTensor(<tf.Tensor: shape=(500, 784), dtype=float32, numpy=
                 array([[4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        ...,
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00]], dtype

Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 68us/sample - loss: 1.4990 - accuracy: 0.9636 - val_loss: 1.4952 - val_accuracy: 0.9671
Epoch 2/2
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4910 - accuracy: 0.9717 - val_loss: 1.4906 - val_accuracy: 0.9711
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 59us/sample - loss: 1.4837 - accuracy: 0.9784 - val_loss: 1.4878 - val_accuracy: 0.9741
Epoch 2/2
60000/60000 [==============================] - 4s 61us/sample - loss: 1.4803 - accuracy: 0.9819 - val_loss: 1.4889 - val_accuracy: 0.9729
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 59us/sample - loss: 1.4773 - accuracy: 0.9847 - val_loss: 1.4839 - val_accuracy: 0.9780
Epoch 2/2
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4750 - accuracy: 0.9868 - va


7it [1:33:21, 805.13s/it]

self.p 2
flatten(p) TensorFlowTensor(<tf.Tensor: shape=(500, 784), dtype=float32, numpy=
                 array([[4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        ...,
                        [4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00]], dtype

Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 67us/sample - loss: 1.4989 - accuracy: 0.9640 - val_loss: 1.5002 - val_accuracy: 0.9625
Epoch 2/2
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4905 - accuracy: 0.9720 - val_loss: 1.4950 - val_accuracy: 0.9675
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 59us/sample - loss: 1.4838 - accuracy: 0.9783 - val_loss: 1.4894 - val_accuracy: 0.9726
Epoch 2/2
60000/60000 [==============================] - 4s 65us/sample - loss: 1.4807 - accuracy: 0.9814 - val_loss: 1.4876 - val_accuracy: 0.9743
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 61us/sample - loss: 1.4776 - accuracy: 0.9844 - val_loss: 1.4841 - val_accuracy: 0.9776
Epoch 2/2
60000/60000 [==============================] - 4s 63us/sample - loss: 1.4751 - accuracy: 0.9868 - va


8it [1:48:31, 836.84s/it]

self.p 2
flatten(p) TensorFlowTensor(<tf.Tensor: shape=(500, 784), dtype=float32, numpy=
                 array([[4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        ...,
                        [4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        [4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00]], dtype

Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 66us/sample - loss: 1.4980 - accuracy: 0.9646 - val_loss: 1.4954 - val_accuracy: 0.9668
Epoch 2/2
60000/60000 [==============================] - 4s 59us/sample - loss: 1.4903 - accuracy: 0.9721 - val_loss: 1.4931 - val_accuracy: 0.9687
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 59us/sample - loss: 1.4838 - accuracy: 0.9783 - val_loss: 1.4879 - val_accuracy: 0.9739
Epoch 2/2
60000/60000 [==============================] - 4s 62us/sample - loss: 1.4811 - accuracy: 0.9810 - val_loss: 1.4908 - val_accuracy: 0.9706
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 62us/sample - loss: 1.4775 - accuracy: 0.9845 - val_loss: 1.4854 - val_accuracy: 0.9765
Epoch 2/2
60000/60000 [==============================] - 4s 63us/sample - loss: 1.4750 - accuracy: 0.9869 - va


9it [2:05:01, 833.46s/it]
 10%|█         | 1/10 [2:05:01<18:45:09, 7501.11s/it]
0it [00:00, ?it/s]

self.p 2
flatten(p) TensorFlowTensor(<tf.Tensor: shape=(500, 784), dtype=float32, numpy=
                 array([[4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        ...,
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00]], dtype

final pruning and eval
Train on 60000 samples, validate on 10000 samples
Epoch 1/100
60000/60000 [==============================] - 4s 66us/sample - loss: 1.4978 - accuracy: 0.9653 - val_loss: 1.5001 - val_accuracy: 0.9621
Epoch 2/100
60000/60000 [==============================] - 4s 61us/sample - loss: 1.4908 - accuracy: 0.9717 - val_loss: 1.4990 - val_accuracy: 0.9635
Epoch 3/100
60000/60000 [==============================] - 4s 61us/sample - loss: 1.4862 - accuracy: 0.9760 - val_loss: 1.4944 - val_accuracy: 0.9677
Epoch 4/100
60000/60000 [==============================] - 4s 63us/sample - loss: 1.4839 - accuracy: 0.9779 - val_loss: 1.4876 - val_accuracy: 0.9739
Epoch 5/100
60000/60000 [==============================] - 4s 63us/sample - loss: 1.4813 - accuracy: 0.9805 - val_loss: 1.4868 - val_accuracy: 0.9751
Epoch 6/100
60000/60000 [==============================] - 4s 63us/sample - loss: 1.4787 - accuracy: 0.9830 - val_loss: 1.4866 - val_accuracy: 0.9746
Epoch 7/100
60000/60000 [==


1it [11:42, 702.06s/it]

self.p 2
flatten(p) TensorFlowTensor(<tf.Tensor: shape=(500, 784), dtype=float32, numpy=
                 array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        ...,
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [2.0861626e-06, 1.7881393e-07, 3.5166740e-06, ..., 1.7881393e-07,
                         1.1324883e-06, 9.2387199e-07]], dtype

Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 66us/sample - loss: 1.4978 - accuracy: 0.9650 - val_loss: 1.4998 - val_accuracy: 0.9623
Epoch 2/2
60000/60000 [==============================] - 4s 59us/sample - loss: 1.4908 - accuracy: 0.9716 - val_loss: 1.4910 - val_accuracy: 0.9703
final pruning and eval
Train on 60000 samples, validate on 10000 samples
Epoch 1/100
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4842 - accuracy: 0.9779 - val_loss: 1.4901 - val_accuracy: 0.9715
Epoch 2/100
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4809 - accuracy: 0.9812 - val_loss: 1.4874 - val_accuracy: 0.9746
Epoch 3/100
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4791 - accuracy: 0.9829 - val_loss: 1.4855 - val_accuracy: 0.9764
Epoch 4/100
60000/60000 [==============================] - 4s 62us/sample - loss: 1.4768 - accuracy: 0.9850 - val_loss: 1.4851 - va


2it [23:40, 706.87s/it]

self.p 2
flatten(p) TensorFlowTensor(<tf.Tensor: shape=(500, 784), dtype=float32, numpy=
                 array([[0., 0., 0., ..., 0., 0., 0.],
                        [0., 0., 0., ..., 0., 0., 0.],
                        [0., 0., 0., ..., 0., 0., 0.],
                        ...,
                        [0., 0., 0., ..., 0., 0., 0.],
                        [0., 0., 0., ..., 0., 0., 0.],
                        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>)
norms TensorFlowTensor(<tf.Tensor: shape=(500,), dtype=float32, numpy=
                 array([9.55769634e+00, 1.01887922e+01, 7.69860315e+00, 7.64230442e+00,
                        8.78968334e+00, 9.82331848e+00, 7.84854794e+00, 1.10874434e+01,
                        5.97471809e+00, 8.43502331e+00, 9.91496086e+00, 6.75492477e+00,
                        1.10000086e+01, 9.63416100e+00, 2.96437293e-01, 9.20947552e+00,
                        8.95141888e+00, 9.41311455e+00, 6.35417938e+00, 7.56579924e+00,
                       

Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 64us/sample - loss: 1.4989 - accuracy: 0.9639 - val_loss: 1.4944 - val_accuracy: 0.9685
Epoch 2/2
60000/60000 [==============================] - 4s 59us/sample - loss: 1.4909 - accuracy: 0.9716 - val_loss: 1.4891 - val_accuracy: 0.9731
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 59us/sample - loss: 1.4842 - accuracy: 0.9781 - val_loss: 1.4877 - val_accuracy: 0.9739
Epoch 2/2
60000/60000 [==============================] - 4s 72us/sample - loss: 1.4806 - accuracy: 0.9815 - val_loss: 1.4857 - val_accuracy: 0.9760
final pruning and eval
Train on 60000 samples, validate on 10000 samples
Epoch 1/100
60000/60000 [==============================] - 4s 69us/sample - loss: 1.4773 - accuracy: 0.9846 - val_loss: 1.4853 - val_accuracy: 0.9763
Epoch 2/100
60000/60000 [==============================] - 4s 65us/sample - loss: 1.4


3it [34:46, 694.67s/it]

self.p 2
flatten(p) TensorFlowTensor(<tf.Tensor: shape=(500, 784), dtype=float32, numpy=
                 array([[2.3841858e-07, 1.0728836e-06, 2.9802322e-07, ..., 2.0861626e-07,
                         3.2782555e-07, 1.7881393e-07],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        ...,
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00]], dtype

Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 67us/sample - loss: 1.4989 - accuracy: 0.9636 - val_loss: 1.4950 - val_accuracy: 0.9666
Epoch 2/2
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4910 - accuracy: 0.9715 - val_loss: 1.4922 - val_accuracy: 0.9700
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 59us/sample - loss: 1.4840 - accuracy: 0.9782 - val_loss: 1.4913 - val_accuracy: 0.9710
Epoch 2/2
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4806 - accuracy: 0.9814 - val_loss: 1.4868 - val_accuracy: 0.9753
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 59us/sample - loss: 1.4776 - accuracy: 0.9845 - val_loss: 1.4853 - val_accuracy: 0.9762
Epoch 2/2
60000/60000 [==============================] - 4s 61us/sample - loss: 1.4752 - accuracy: 0.9867 - va


4it [46:09, 691.08s/it]

self.p 2
flatten(p) TensorFlowTensor(<tf.Tensor: shape=(500, 784), dtype=float32, numpy=
                 array([[1.7881393e-07, 1.2421608e-04, 5.9604645e-08, ..., 8.9406967e-08,
                         1.1920929e-07, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [1.0728836e-06, 1.1026859e-06, 6.5565109e-07, ..., 1.1622906e-06,
                         1.2814999e-06, 1.2516975e-06],
                        ...,
                        [8.9406967e-08, 1.7881393e-07, 2.4139881e-06, ..., 1.4901161e-07,
                         2.9802322e-08, 5.9604645e-08],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00]], dtype

Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 70us/sample - loss: 1.4981 - accuracy: 0.9647 - val_loss: 1.4953 - val_accuracy: 0.9677
Epoch 2/2
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4913 - accuracy: 0.9710 - val_loss: 1.4908 - val_accuracy: 0.9715
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4838 - accuracy: 0.9785 - val_loss: 1.4905 - val_accuracy: 0.9710
Epoch 2/2
60000/60000 [==============================] - 4s 62us/sample - loss: 1.4803 - accuracy: 0.9818 - val_loss: 1.4903 - val_accuracy: 0.9711
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4775 - accuracy: 0.9847 - val_loss: 1.4862 - val_accuracy: 0.9762
Epoch 2/2
60000/60000 [==============================] - 4s 61us/sample - loss: 1.4751 - accuracy: 0.9868 - va


5it [58:32, 706.81s/it]

self.p 2
flatten(p) TensorFlowTensor(<tf.Tensor: shape=(500, 784), dtype=float32, numpy=
                 array([[4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.2021275e-06,
                         4.7683716e-07, 8.9406967e-08],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [1.0430813e-06, 1.0132790e-06, 2.3841858e-07, ..., 1.1324883e-06,
                         1.7881393e-07, 1.0728836e-06],
                        ...,
                        [1.4901161e-07, 2.3543835e-06, 4.7683716e-07, ..., 1.1920929e-07,
                         9.8347664e-07, 2.0861626e-07],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00]], dtype

Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 66us/sample - loss: 1.4985 - accuracy: 0.9642 - val_loss: 1.4940 - val_accuracy: 0.9683
Epoch 2/2
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4904 - accuracy: 0.9720 - val_loss: 1.4921 - val_accuracy: 0.9693
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 59us/sample - loss: 1.4837 - accuracy: 0.9783 - val_loss: 1.4871 - val_accuracy: 0.9744
Epoch 2/2
60000/60000 [==============================] - 4s 61us/sample - loss: 1.4806 - accuracy: 0.9815 - val_loss: 1.4861 - val_accuracy: 0.9755
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4774 - accuracy: 0.9845 - val_loss: 1.4860 - val_accuracy: 0.9757
Epoch 2/2
60000/60000 [==============================] - 4s 61us/sample - loss: 1.4752 - accuracy: 0.9867 - va


6it [1:10:28, 709.48s/it]

self.p 2
flatten(p) TensorFlowTensor(<tf.Tensor: shape=(500, 784), dtype=float32, numpy=
                 array([[4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        ...,
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00]], dtype

Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 66us/sample - loss: 1.4985 - accuracy: 0.9645 - val_loss: 1.5023 - val_accuracy: 0.9608
Epoch 2/2
60000/60000 [==============================] - 4s 61us/sample - loss: 1.4911 - accuracy: 0.9713 - val_loss: 1.4925 - val_accuracy: 0.9691
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4841 - accuracy: 0.9780 - val_loss: 1.4904 - val_accuracy: 0.9722
Epoch 2/2
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4810 - accuracy: 0.9811 - val_loss: 1.4855 - val_accuracy: 0.9755
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4776 - accuracy: 0.9845 - val_loss: 1.4849 - val_accuracy: 0.9771
Epoch 2/2
60000/60000 [==============================] - 4s 61us/sample - loss: 1.4755 - accuracy: 0.9865 - va


7it [1:25:14, 762.58s/it]

self.p 2
flatten(p) TensorFlowTensor(<tf.Tensor: shape=(500, 784), dtype=float32, numpy=
                 array([[4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        ...,
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00]], dtype

Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 66us/sample - loss: 1.4982 - accuracy: 0.9650 - val_loss: 1.5016 - val_accuracy: 0.9608
Epoch 2/2
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4915 - accuracy: 0.9710 - val_loss: 1.4923 - val_accuracy: 0.9693
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4839 - accuracy: 0.9781 - val_loss: 1.4865 - val_accuracy: 0.9757
Epoch 2/2
60000/60000 [==============================] - 4s 62us/sample - loss: 1.4810 - accuracy: 0.9808 - val_loss: 1.4908 - val_accuracy: 0.9703
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 61us/sample - loss: 1.4777 - accuracy: 0.9846 - val_loss: 1.4857 - val_accuracy: 0.9757
Epoch 2/2
60000/60000 [==============================] - 4s 63us/sample - loss: 1.4754 - accuracy: 0.9865 - va


8it [1:39:21, 787.79s/it]

self.p 2
flatten(p) TensorFlowTensor(<tf.Tensor: shape=(500, 784), dtype=float32, numpy=
                 array([[4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        ...,
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00]], dtype

Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 64us/sample - loss: 1.4986 - accuracy: 0.9642 - val_loss: 1.4951 - val_accuracy: 0.9669
Epoch 2/2
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4910 - accuracy: 0.9713 - val_loss: 1.4929 - val_accuracy: 0.9689
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 59us/sample - loss: 1.4840 - accuracy: 0.9784 - val_loss: 1.4894 - val_accuracy: 0.9720
Epoch 2/2
60000/60000 [==============================] - 4s 61us/sample - loss: 1.4808 - accuracy: 0.9811 - val_loss: 1.4869 - val_accuracy: 0.9750
Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 4s 59us/sample - loss: 1.4773 - accuracy: 0.9850 - val_loss: 1.4850 - val_accuracy: 0.9773
Epoch 2/2
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4746 - accuracy: 0.9873 - va


9it [1:56:00, 773.37s/it]
 20%|██        | 2/10 [4:01:01<16:18:31, 7338.88s/it]
0it [00:00, ?it/s]

self.p 2
flatten(p) TensorFlowTensor(<tf.Tensor: shape=(500, 784), dtype=float32, numpy=
                 array([[4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                         0.0000000e+00, 0.0000000e+00],
                        [4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        ...,
                        [4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        [4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07],
                        [4.7683716e-07, 4.7683716e-07, 4.7683716e-07, ..., 4.7683716e-07,
                         4.7683716e-07, 4.7683716e-07]], dtype

final pruning and eval
Train on 60000 samples, validate on 10000 samples
Epoch 1/100
60000/60000 [==============================] - 4s 66us/sample - loss: 1.4983 - accuracy: 0.9644 - val_loss: 1.4973 - val_accuracy: 0.9648
Epoch 2/100
60000/60000 [==============================] - 4s 60us/sample - loss: 1.4908 - accuracy: 0.9716 - val_loss: 1.4922 - val_accuracy: 0.9694
Epoch 3/100
60000/60000 [==============================] - 4s 61us/sample - loss: 1.4858 - accuracy: 0.9762 - val_loss: 1.4908 - val_accuracy: 0.9709
Epoch 4/100
60000/60000 [==============================] - 4s 61us/sample - loss: 1.4839 - accuracy: 0.9781 - val_loss: 1.4896 - val_accuracy: 0.9720
Epoch 5/100
60000/60000 [==============================] - 4s 61us/sample - loss: 1.4810 - accuracy: 0.9811 - val_loss: 1.4873 - val_accuracy: 0.9742
Epoch 6/100
60000/60000 [==============================] - 4s 62us/sample - loss: 1.4797 - accuracy: 0.9816 - val_loss: 1.4864 - val_accuracy: 0.9756
Epoch 7/100
60000/60000 [==

0it [06:15, ?it/s]
 20%|██        | 2/10 [4:07:16<16:29:06, 7418.25s/it]


KeyboardInterrupt: 

In [4]:
def get_average_success_rates(all_sucess_rates):
    success_per_pruning_rate=[]
    for i in range(len(all_success_rates)):
        for j in range(len(all_success_rates[i])):

            try:
                success_per_pruning_rate[j].append(all_success_rates[i][j])
            except:
                success_per_pruning_rate.append([])
                success_per_pruning_rate[j].append(all_success_rates[i][j])
    avg_success_per_pruning_rate = [sum(x)/len(x) for x in success_per_pruning_rate];avg_success_per_pruning_rate
    return avg_success_per_pruning_rate

In [3]:
def get_average_accuracies(all_accuracies):
    acc_per_pruning_rate=[]
    for i in range(len(all_accuracies)):
        for j in range(len(all_accuracies[i])):

            try:
                acc_per_pruning_rate[j].append(all_accuracies[i][j][1])
            except:
                acc_per_pruning_rate.append([])
                acc_per_pruning_rate[j].append(all_accuracies[i][j][1])
    avg_acc_per_pruning_rate = [sum(x)/len(x) for x in acc_per_pruning_rate]; avg_acc_per_pruning_rate
    return avg_acc_per_pruning_rate

# Helper Functions

In [1]:
def train_model(model, to_convergence=True):
    if to_convergence == True:
        callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)
        model.fit(
            x=x_train,
            y=y_train,
            batch_size=64,
            epochs=100,
            callbacks=[callback],
            validation_data=(x_test, y_test),
            )
    if to_convergence == False:
        model.fit(
            x=x_train,
            y=y_train,
            batch_size=64,
            epochs=2,
            validation_data=(x_test, y_test),
            )
    return model

def prune_weights(model, pruning_ratio):
    weights = model.get_weights()
    weights_to_prune = model.get_weights()
    for index, weight in enumerate(weights):
        if (index == 0) or (index == 3) or (index == 6):
            flat_weights = weight.flatten()
            flat_weights_to_prune = weights_to_prune[index+1].flatten()
            #print (flat_weights_to_prune.shape, flat_weights.shape)
            flat_weights_df = pd.DataFrame(flat_weights)
            flat_weights_to_prune_df = pd.DataFrame(flat_weights_to_prune)
            no_of_weights_to_prune = int(len(flat_weights)*pruning_ratio)
            #print(no_of_weights_to_prune)
            indices_to_delete = flat_weights_df.abs().values.argsort(0)[:no_of_weights_to_prune]
            for idx_to_delete in indices_to_delete:
                flat_weights_to_prune[idx_to_delete] = 0
            dims = weights_to_prune[index+1].shape
            weights_reshaped = flat_weights_to_prune.reshape(dims)
            weights_to_prune[index+1] = weights_reshaped
    #print(weights_to_prune)
    return weights_to_prune

def pgd_attack(model_to_attack):
    fmodel = fb.models.TensorFlowModel(model_to_attack, bounds=(0,1))
    attack = fb.attacks.LinfProjectedGradientDescentAttack()
    adversarials = attack(
        fmodel,
        x,
        y,
        epsilons=[15/255]
    )
    return np.count_nonzero(adversarials[2])/500

def cw2_attack(model_to_attack):
    fmodel = fb.models.TensorFlowModel(model_to_attack, bounds=(0,1))
    attack = fb.attacks.L2CarliniWagnerAttack()
    adversarials = attack(
        fmodel,
        x,
        y,
        epsilons=[.5]
    )
    return np.count_nonzero(adversarials[2])/len(y)

# Load Data

In [ ]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train = x_train.reshape(60000, 784).astype('float32') / 255
x_test = x_test.reshape(10000, 784).astype('float32') / 255

x = tf.convert_to_tensor(x_train[:500].reshape(500,28*28))
y = tf.convert_to_tensor([y_train[:500]])[0];

# Define Model

In [ ]:
class CustomLayer(layers.Layer):

    def __init__(self, units=32, activation='relu'):
        super(CustomLayer, self).__init__()
        self.units = units
        self.activation = activation

    def build(self, input_shape):
        #print(input_shape)
        self.w = self.add_weight(shape=(input_shape[-1], self.units),
                                 initializer='random_normal',
                                 trainable=True,
                                name='unpruned_weights')
        self.mask = self.add_weight(shape=(self.w.shape),
                                    initializer='ones',
                                    trainable=False,
                                   name='pruning_mask')
        self.pruned_w = self.add_weight(shape=(input_shape[-1], self.units),
                                 initializer='ones',
                                 trainable=False,
                                       name='pruned_weights')
        
    def call(self, inputs):
        #self.mask_2 = tf.multiply(self.mask, self.mask_2)
        self.pruned_w = tf.multiply(self.w, self.mask)
        #print(self.pruned_w.eval())
        x = tf.matmul(inputs, self.pruned_w)
        
        if self.activation == 'relu':
            return tf.keras.activations.relu(x)
        if self.activation == 'softmax':
            return tf.keras.activations.softmax(x)
        raise ValueError('Activation function not implemented')

class LeNet300_100(tf.keras.Model):
    def __init__(self):
        super(LeNet300_100, self).__init__()
        self.dense1 = CustomLayer(300)
        self.dense2 = CustomLayer(100)
        self.dense3 = CustomLayer(10, activation='softmax')
        
    def call(self, inputs):
        
        x = self.dense1(inputs)
        #print(x.shape)
        x = self.dense2(x)
        #print(x.shape)
        return self.dense3(x)
    


# Compile and Train Model

In [ ]:
model = LeNet300_100()
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True) ,
              metrics=['accuracy'],
              experimental_run_tf_function=False
              
             )

callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)
model.fit(x=x_train,
          y=y_train,
          batch_size=64,
          epochs=2,
          callbacks=[callback],
          validation_data=(x_test, y_test),
         )
model.save('./saved-models/mini-pipeline-mlp-baseline-model')